name: Typecheck

on:
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Internal Function Deps
        run: cd functions && npm i

      - name: Run Typecheck
        run: npm run build